## Two functions (makeCacheMatrix and cachesolve) will
## cache the inverse of the given matrix

## set L as null, x as matrix and mean as inverse
makeCacheMatrix <- function(x = matrix()) {
  L <- NULL
  set <- function(y) {
    x <<- y
    L <<- NULL  
}

  get <- function() x
  setInverse <- function(inverse) L <<- inverse
  getInverse <-function() L
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}
        
## cacheSolve : Calculates the inverse of the cache matrix
## that was generated by the first function
cacheSolve <- function(x, ...) {
  L <- x$getInverse()
  if (!is.null(L)) {
    message("Getting Cached Data")
    return(L)
  }
  m <- x$get()
  L <- solve(m, ...)
  x$setInverse(L)
  L
}
